### ISSUE TITLE
v1 Milestone

### ISSUE THREAD

**Issue by bcwaldon** [bcwaldon/klondike#1]
The project is generally useful, but several important pieces remain:
- [x] manage secrets securely
- [x] disable CoreOS auto-updates using cloud-config
- [x] spin TLS certificates per worker
- [x] enable AWS Kubernetes cloudprovider
- [x] deploy datadog agent via DaemonSet
- [x] reserve host memory for kubelets
- [x] expand README
- [x] mount /dev/xvdb at /var/lib/docker
- [x] create Route53 record for ELB
